/*
 * generated by Xtext
 */
package org.eclipse.gemoc.gexpressions.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.gemoc.gexpressions.xtext.ui.internal.GExpressionsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GExpressionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GExpressionsActivator.getInstance().getInjector(GExpressionsActivator.ORG_ECLIPSE_GEMOC_GEXPRESSIONS_XTEXT_GEXPRESSIONS);
	}
	
}
