/*
 * generated by Xtext
 */
package org.eclipse.gemoc.gexpressions.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GExpressionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/gemoc/gexpressions/xtext/parser/antlr/internal/InternalGExpressions.tokens");
	}
}
