/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.dsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.eclipse.gemoc.dsl.DslPackage;
import org.eclipse.gemoc.dsl.EntryValue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entry Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.gemoc.dsl.impl.EntryValueImpl#getEntryLines <em>Entry Lines</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EntryValueImpl extends MinimalEObjectImpl.Container implements EntryValue
{
  /**
   * The cached value of the '{@link #getEntryLines() <em>Entry Lines</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntryLines()
   * @generated
   * @ordered
   */
  protected EList<String> entryLines;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntryValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.ENTRY_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getEntryLines()
  {
    if (entryLines == null)
    {
      entryLines = new EDataTypeEList<String>(String.class, this, DslPackage.ENTRY_VALUE__ENTRY_LINES);
    }
    return entryLines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.ENTRY_VALUE__ENTRY_LINES:
        return getEntryLines();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.ENTRY_VALUE__ENTRY_LINES:
        getEntryLines().clear();
        getEntryLines().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ENTRY_VALUE__ENTRY_LINES:
        getEntryLines().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ENTRY_VALUE__ENTRY_LINES:
        return entryLines != null && !entryLines.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (entryLines: ");
    result.append(entryLines);
    result.append(')');
    return result.toString();
  }

} //EntryValueImpl
