services:
  gemoc_full_compilation:
    image: "gemoc/gemoc-full-compilation:latest"
    build: "."
    environment:
      UID: 1000
      GID: 1000
    volumes:
      - "./cache-m2:/home/ubuntu/.m2"
      - "../../../..:/home/ubuntu/src"
      
