version: '3'
services:
  gemoc_full_compilation:
    image: "gemoc/gemoc-full-compilation:latest"
    build: "."
    volumes:
      - "./cache-m2:/home/jenkins/.m2"
      - "../../../..:/home/jenkins/src"
      
