/*******************************************************************************
 * Copyright (c) 2017 Inria and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Inria - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.gemoc.gexpressions.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GExpressionsRuntimeModule extends org.eclipse.gemoc.gexpressions.xtext.AbstractGExpressionsRuntimeModule {

}
