/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Syntax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.gemoc.dsl.AbstractSyntax#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.eclipse.gemoc.dsl.DslPackage#getAbstractSyntax()
 * @model
 * @generated
 */
public interface AbstractSyntax extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.gemoc.dsl.Value}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see org.eclipse.gemoc.dsl.DslPackage#getAbstractSyntax_Values()
   * @model containment="true"
   * @generated
   */
  EList<Value> getValues();

} // AbstractSyntax
