/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getDisplayName <em>Display Name</em>}</li>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getMetaprog <em>Metaprog</em>}</li>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getAbstractSyntax <em>Abstract Syntax</em>}</li>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getSemantic <em>Semantic</em>}</li>
 *   <li>{@link org.eclipse.gemoc.dsl.Dsl#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.eclipse.gemoc.dsl.DslPackage#getDsl()
 * @model
 * @generated
 */
public interface Dsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.dsl.Dsl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Display Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Display Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Display Name</em>' containment reference.
   * @see #setDisplayName(DisplayName)
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_DisplayName()
   * @model containment="true"
   * @generated
   */
  DisplayName getDisplayName();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.dsl.Dsl#getDisplayName <em>Display Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Display Name</em>' containment reference.
   * @see #getDisplayName()
   * @generated
   */
  void setDisplayName(DisplayName value);

  /**
   * Returns the value of the '<em><b>Metaprog</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Metaprog</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metaprog</em>' containment reference.
   * @see #setMetaprog(Metaprog)
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_Metaprog()
   * @model containment="true"
   * @generated
   */
  Metaprog getMetaprog();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.dsl.Dsl#getMetaprog <em>Metaprog</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metaprog</em>' containment reference.
   * @see #getMetaprog()
   * @generated
   */
  void setMetaprog(Metaprog value);

  /**
   * Returns the value of the '<em><b>Abstract Syntax</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract Syntax</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Syntax</em>' containment reference.
   * @see #setAbstractSyntax(AbstractSyntax)
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_AbstractSyntax()
   * @model containment="true"
   * @generated
   */
  AbstractSyntax getAbstractSyntax();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.dsl.Dsl#getAbstractSyntax <em>Abstract Syntax</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abstract Syntax</em>' containment reference.
   * @see #getAbstractSyntax()
   * @generated
   */
  void setAbstractSyntax(AbstractSyntax value);

  /**
   * Returns the value of the '<em><b>Semantic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semantic</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semantic</em>' containment reference.
   * @see #setSemantic(Semantic)
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_Semantic()
   * @model containment="true"
   * @generated
   */
  Semantic getSemantic();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.dsl.Dsl#getSemantic <em>Semantic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semantic</em>' containment reference.
   * @see #getSemantic()
   * @generated
   */
  void setSemantic(Semantic value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.gemoc.dsl.Value}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see org.eclipse.gemoc.dsl.DslPackage#getDsl_Values()
   * @model containment="true"
   * @generated
   */
  EList<Value> getValues();

} // Dsl
