/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.gemoc

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
	
	 override Class<? extends IValueConverterService> bindIValueConverterService() {
        return ValueConverterService
    }
}
