/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
