/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.dsl.tests

import com.google.inject.Inject
import org.eclipse.gemoc.dsl.Dsl
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

import static extension org.junit.Assert.*
import org.eclipse.gemoc.tests.DslInjectorProvider

@RunWith(XtextRunner)
@InjectWith(DslInjectorProvider)
class DslParsingEmptyLineTest {
	@Inject
	ParseHelper<Dsl> parseHelper

	@Test
	def void minimal_empty_ending_line() {
		val result = parseHelper.parse('''
			name = my.language
			
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}

	@Test
	def void minimal_empty_ending_line_with_WS() {
		val result = parseHelper.parse('''
			name = my.language
			   
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}

	@Test
	def void minimal_empty_line() {
		val result = parseHelper.parse('''
			name = my.language
			
			mykey = myvalue
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}

	@Test
	def void minimal_empty_line_with_WS() {
		val result = parseHelper.parse('''
			name = my.language
			   
			mykey = myvalue
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}
	
	@Test
	def void multiple_empty_lines() {
		val result = parseHelper.parse('''
			name = my.language
			
			
			mykey = myvalue
			
			
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}

	@Test
	def void multiple_empty_lines_with_WS() {
		val result = parseHelper.parse('''
			name = my.language
			   
			   
			mykey = myvalue
			   
			   
		''')
		assertNotNull(result)
		assertTrue(
			"eResource.errors not Empty " + result.eResource.errors,
			result.eResource.errors.isEmpty
		)
		// assertEquals("my.language", result.name)
		assertTrue("no key named \"name\"", result.entries.exists[e|e.key == "name"])
		assertEquals("my.language", result.entries.findFirst[e|e.key == "name"].value.entryLines.get(0))
	}
}
