/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.ide

import com.google.inject.Guice
import org.eclipse.gemoc.DslRuntimeModule
import org.eclipse.gemoc.DslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DslIdeSetup extends DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DslRuntimeModule, new DslIdeModule))
	}
	
}
